# Generated by Django 4.2.7 on 2023-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sui_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DPIIT', models.CharField(blank=True, max_length=500, null=True)),
                ('companyName', models.CharField(blank=True, max_length=500, null=True)),
                ('stage', models.CharField(blank=True, max_length=500, null=True)),
                ('focusIndustry', models.CharField(blank=True, max_length=500, null=True)),
                ('focusSector', models.CharField(blank=True, max_length=500, null=True)),
                ('serviceArea', models.CharField(blank=True, max_length=5000, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('noOfYear', models.CharField(blank=True, max_length=10, null=True)),
                ('companyURL', models.CharField(blank=True, max_length=500, null=True)),
                ('aboutDetails', models.TextField(blank=True, null=True)),
                ('joinedDate', models.CharField(blank=True, max_length=500, null=True)),
                ('DPIITRecognised', models.CharField(blank=True, max_length=500, null=True)),
                ('activeSince', models.CharField(blank=True, max_length=500, null=True)),
                ('dateofScrapping', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
