# Generated by Django 4.2.7 on 2024-01-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sui_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sui_api',
            table='sui_final',
        ),
    ]
