# Generated by Django 4.2.7 on 2024-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sui_api', '0002_alter_sui_api_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sui_api',
            name='Updated_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sui_api',
            name='pageurl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sui_api',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
