# Generated by Django 5.0.6 on 2024-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sui_api', '0003_sui_api_updated_date_sui_api_pageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sui_api',
            old_name='id',
            new_name='sr_no',
        ),
        migrations.AddField(
            model_name='sui_api',
            name='cin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sui_api',
            name='company_availability_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sui_api',
            name='dipp_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sui_api',
            name='legalName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sui_api',
            name='pan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
